<?php
$totalPerPage = ($this->show_total) ? $this->show_total : 8;
$visibility = array(
Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
);
$storeId = Mage::app()->getStore()->getId();
$_productCollection = Mage::getResourceModel('reports/product_collection')
->addAttributeToSelect('*')
->setStoreId($storeId)
->addStoreFilter($storeId)
->addAttributeToFilter('visibility', $visibility)
->addAttributeToFilter('featured', true)
->setOrder('created_at', 'desc')
->addAttributeToSelect('status')
->setPageSize($totalPerPage);

Mage::getSingleton('catalog/product_status') -> addVisibleFilterToCollection($_productCollection);
Mage::getSingleton('cataloginventory/stock') -> addInStockFilterToCollection($_productCollection);
Mage::getSingleton('catalog/product_visibility') -> addVisibleInSearchFilterToCollection($_productCollection);
$theme = $this->helper('themesetting');
	$labelsHelper = $this->helper('themesetting/labels');
	$templateHelper = $this->helper('themesetting/template');

	
	//Default image size
	$imgWidth = 180;
	$imgHeight = 180;
	//$_columnCount = $this->getColumnCount();
	
	//Aspect ratio settings
	if ($theme->getCfg('category/aspect_ratio'))
		$imgHeight = 0; //Height will be computed automatically (based on width) to keep the aspect ratio

	//Modify slider depending on number of slides
	$sliderClasses = '';
	if($_collectionSize > 0)
	{
		if($_collectionSize <= 15)
			$sliderClasses .= " count-$_collectionSize";
		else
			$sliderClasses .= " count-multi";
	}
?>
<div class="new-itemslider-wrapper itemslider-wrapper-home" id="slide-ie78">
	<h3 class="section-title">Featured Products</h3>
    <div class="itemslider itemslider-horizontal itemslider-x">
        <ul class="slides-home products-grid-home">
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item">
                    <div class="wrapper-item">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image">
<img style="height:180px; width:180px;" src="<?php echo $_product->getExternalUrl(); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
                    <?php /*?><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" class="product-image">                    
                        <img src="<?php echo $_product->getExternalUrl(); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" width="180" /></a>
                        
<?php */?>                        <?php /*if ($theme->getCfg('category/alt_image')): ?>
							<?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
						<?php endif;*/?>
		
        <div class="infomaton-item">  
                    <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
                  
                    <?php //echo $this->getPriceHtml($_product, true, '-new') ?>
                                 <div class="price-box">
                                                                <span class="regular-price" id="product-price-122-new">
                                            <span class="price"><?php echo $this->helper('checkout')->formatPrice($_product->getPrice()) ?></span>                                    </span>
                        
        </div>
                      
         
                      <?php echo $this->getReviewsSummaryHtml($_product, "short", true); //reviews ?>   
                   
                                    
                    
            </div>
                    
               <?php 
              
                    $storeId    = Mage::app()->getStore()->getId();
                     $summaryData = Mage::getModel('review/review_summary')
                       ->setStoreId($storeId)
                       ->load('product_id');
                        print_r($summaryData->getRatingSummary());
                       if($summaryData->getRatingSummary()){ 
       ?>
       
        
             <?php  }?>       
  
      </div> 
              
                </li>
                
            <?php endforeach; ?>
            <div class="clearer"></div>
        </ul> <!-- end: slides -->
    </div> <!-- end: itemslider -->

</div>


