<?php
/**
 * - Main "foreach" loop is based on: \BASE\DEFAULT\template\catalog\product\list.phtml
 *   with some small changes:
 *		- h2 replaced with h3
 */
?>
<?php
	$_productCollection = $this->getLoadedProductCollection();
?>
<?php if ($_productCollection && ($_collectionSize = $_productCollection->count())): ?>
<?php
	$_helper = $this->helper('catalog/output');
	$theme = $this->helper('themesetting');
	$labelsHelper = $this->helper('themesetting/labels');
	$templateHelper = $this->helper('themesetting/template');
	
	//Default image size
	$imgWidth =180;
	$imgHeight = 180;
	//$_columnCount = $this->getColumnCount();
	
	//Aspect ratio settings
	if ($theme->getCfg('category/aspect_ratio'))
		$imgHeight = 0; //Height will be computed automatically (based on width) to keep the aspect ratio

	//Modify slider depending on number of slides
	$sliderClasses = '';
	if($_collectionSize > 0)
	{
		if($_collectionSize <= 5)
			$sliderClasses .= " count-$_collectionSize";
		else
			$sliderClasses .= " count-multi";
	}
	
	//Create random value
	list($usec, $sec) = explode(' ', microtime());
	//$randomSeed = ;
    mt_srand( (float) $sec + ((float) $usec * 100000) );
    $r = mt_rand();
?>


<div class="itemslider-wrapper  itemslider-wrapper-featured   itemslider-wrapper-<?php echo $r; ?>">
<h3 class="section-title">Featured Products</h3><div class="itemslider-border">
	<div class="nav-wrapper gen-slider-arrows1 gen-slider-arrows1-pos-top-right"></div>
    
    <div class="itemslider itemslider-wrapper-home  itemslider-horizontal itemslider-x<?php if($sliderClasses) echo $sliderClasses; ?>">
        <ul class="slides products-grid-slide products-grid-home">
            <?php foreach ($_productCollection as $_product): ?>
			               <li class="item">
			                    <div class="wrapper-item">
			                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" class="product-image">
			                    
			                        <img src="<?php echo $theme->getImgUrl($this, $_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
			                        
			                        <?php if ($theme->getCfg('category/alt_image')): ?>
										<?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
									<?php endif; ?>
					
			        <div class="infomaton-item">  
			                    <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
			                  
			                    <?php echo $this->getPriceHtml($_product, true, '-new') ?><br>
			                    <div class="shopnow">
			                    	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">Shop Now </a>
			                    </div>  <!-- -end shop now -->
			        
			                    
			            </div>
			                    
			               <?php 
			              
			                    $storeId    = Mage::app()->getStore()->getId();
			                     $summaryData = Mage::getModel('review/review_summary')
			                       ->setStoreId($storeId)
			                       ->load('product_id');
			                        print_r($summaryData->getRatingSummary());
			                       if($summaryData->getRatingSummary()){ 
			       ?>
			       
			        
			             <?php  }?>       
			  
			      </div> 
			              
			                </li>
            <?php endforeach; ?>
        </ul> <!-- end: slides -->
    </div> <!-- end: itemslider --></div>

</div> <!-- end: itemslider-wrapper -->
<script type="text/javascript">
//<![CDATA[
	jQuery(function($) {
		$('.itemslider-wrapper-<?php echo $r; ?> .itemslider').flexslider({
			namespace: "",
			animation: "slide",
			easing: "easeInQuart",
			
			<?php if($time = intval($theme->getCfg('product_slider/timeout'))): ?>
				slideshowSpeed: <?php echo $time; ?>,
				animationLoop: true,
			<?php else: ?>
				slideshow: false,
				animationLoop: false,
			<?php endif; ?>
			
			<?php if($speed = intval($theme->getCfg('product_slider/speed'))): ?>
				animationSpeed: <?php echo $speed; ?>,
			<?php endif; ?>
			
			pauseOnHover: true,
			controlNav: false,
			
			controlsContainer: ".itemslider-wrapper-<?php echo $r; ?> .nav-wrapper",
			
			itemWidth: 190,
			move: <?php echo intval($theme->getCfg('product_slider/move_items')); ?>
		});
	});
//]]>
</script>
<?php endif; ?>
